services:
  - type: web
    name: academia-flora-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: DB_URL
        value: jdbc:h2:file:./data/academiaflora
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        value: ""
